# Utilisation d'une image de base Node.js
FROM node:18.12.0

# Définir le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copier les fichiers package.json et package-lock.json (si existent)
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .
ENV NODE_DEBUG=request
# Définir le port exposé par l'application Node.js
EXPOSE 4000

# Commande pour démarrer l'application
CMD ["node", "index.js"]  
